"""empty message

Revision ID: 5b7c3c7b0d01
Revises: 8bcc02c9bd07
Create Date: 2025-08-21 18:24:04.029612

"""
from alembic import op
import models as models
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b7c3c7b0d01'
down_revision = '8bcc02c9bd07'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_custom_config',
    sa.Column('id', models.types.StringUUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('app_id', models.types.StringUUID(), nullable=False),
    sa.Column('activityUuid', sa.String(length=255), nullable=False),
    sa.Column('procedureVersionId', sa.String(length=255), nullable=False),
    sa.Column('modelType', sa.String(length=255), nullable=False),
    sa.Column('procedureId', sa.String(length=255), nullable=True),
    sa.Column('valueChainId', sa.String(length=255), nullable=True),
    sa.Column('valueFlowVersionId', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id', name='app_custom_config_pkey')
    )
    with op.batch_alter_table('app_custom_config', schema=None) as batch_op:
        batch_op.create_index('config_app_id_idx', ['app_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('app_custom_config', schema=None) as batch_op:
        batch_op.drop_index('config_app_id_idx')

    op.drop_table('app_custom_config')
    # ### end Alembic commands ###
