"""empty message

Revision ID: c457175538ee
Revises: 304fdcb0457e
Create Date: 2025-09-17 18:25:42.885703

"""
from alembic import op
import models as models
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c457175538ee'
down_revision = '304fdcb0457e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('provider_model_descriptions',
    sa.Column('model_id', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('model_id', name='provider_model_description_pkey')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('provider_model_descriptions')
    # ### end Alembic commands ###
