"""empty message

Revision ID: d867b4142719
Revises: 8bcc02c9bd07
Create Date: 2025-09-15 13:44:57.496438

"""
from alembic import op
import models as models
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd867b4142719'
down_revision = '8bcc02c9bd07'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_custom_config',
    sa.Column('id', models.types.StringUUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('app_id', models.types.StringUUID(), nullable=False),
    sa.Column('upgradeStatus', sa.Boolean(), nullable=False),
    sa.Column('bindStatus', sa.Boolean(), nullable=False),
    sa.Column('enable', sa.Boolean(), nullable=False),
    sa.Column('activityLabelId', sa.String(length=255), nullable=True),
    sa.Column('activityBasicId', sa.String(length=255), nullable=True),
    sa.Column('processId', sa.String(length=255), nullable=True),
    sa.Column('executeFlowVersionId', sa.String(length=255), nullable=True),
    sa.Column('modelType', sa.String(length=255), nullable=True),
    sa.Column('procedureId', sa.String(length=255), nullable=True),
    sa.Column('valueChainId', sa.String(length=255), nullable=True),
    sa.Column('valueFlowVersionId', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id', name='app_custom_config_pkey')
    )
    with op.batch_alter_table('app_custom_config', schema=None) as batch_op:
        batch_op.create_index('config_app_id_idx', ['app_id'], unique=False)

    with op.batch_alter_table('tenants', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cbrain_tenant_id', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('is_public', sa.Boolean(), server_default=sa.text('true'), nullable=False))
        batch_op.create_index('tenant_cbrain_tenant_id_idx', ['cbrain_tenant_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tenants', schema=None) as batch_op:
        batch_op.drop_index('tenant_cbrain_tenant_id_idx')
        batch_op.drop_column('is_public')
        batch_op.drop_column('cbrain_tenant_id')

    with op.batch_alter_table('app_custom_config', schema=None) as batch_op:
        batch_op.drop_index('config_app_id_idx')

    op.drop_table('app_custom_config')
    # ### end Alembic commands ###
