"""empty message

Revision ID: eccc442007f6
Revises: 4c9b00dc72c2
Create Date: 2025-08-22 14:40:43.857669

"""
from alembic import op
import models as models
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eccc442007f6'
down_revision = '4c9b00dc72c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tenants', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cbrain_tenant_id', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('is_public', sa.Boolean(), server_default=sa.text('true'), nullable=False))
        batch_op.create_index('tenant_cbrain_tenant_id_idx', ['cbrain_tenant_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tenants', schema=None) as batch_op:
        batch_op.drop_index('tenant_cbrain_tenant_id_idx')
        batch_op.drop_column('is_public')
        batch_op.drop_column('cbrain_tenant_id')

    # ### end Alembic commands ###
