"""empty message

Revision ID: f6444b1b7856
Revises: eccc442007f6
Create Date: 2025-08-26 15:50:19.244065

"""
from alembic import op
import models as models
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f6444b1b7856'
down_revision = 'eccc442007f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('app_custom_config', schema=None) as batch_op:
        batch_op.add_column(sa.Column('activityLabelId', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('activityNodeId', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('processId', sa.String(length=255), nullable=True))
        batch_op.drop_column('procedureVersionId')
        batch_op.drop_column('activityUuid')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('app_custom_config', schema=None) as batch_op:
        batch_op.add_column(sa.Column('activityUuid', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('procedureVersionId', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.drop_column('processId')
        batch_op.drop_column('activityNodeId')
        batch_op.drop_column('activityLabelId')

    # ### end Alembic commands ###
