"""empty message

Revision ID: 304fdcb0457e
Revises: d867b4142719
Create Date: 2025-09-17 14:09:28.489825

"""
from alembic import op
import models as models
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '304fdcb0457e'
down_revision = 'd867b4142719'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('app_custom_config', schema=None) as batch_op:
        batch_op.create_index('config_activityLabelId_idx', ['activityLabelId'], unique=False)
        batch_op.create_index('config_valueChainId_idx', ['valueChainId'], unique=False)

    with op.batch_alter_table('apps', schema=None) as batch_op:
        batch_op.add_column(sa.Column('scene_type', sa.String(length=32), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('apps', schema=None) as batch_op:
        batch_op.drop_column('scene_type')

    with op.batch_alter_table('app_custom_config', schema=None) as batch_op:
        batch_op.drop_index('config_valueChainId_idx')
        batch_op.drop_index('config_activityLabelId_idx')

    # ### end Alembic commands ###
