"""empty message

Revision ID: 4c9b00dc72c2
Revises: 5b7c3c7b0d01
Create Date: 2025-08-22 10:34:50.739458

"""
from alembic import op
import models as models
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c9b00dc72c2'
down_revision = '5b7c3c7b0d01'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('app_custom_config', schema=None) as batch_op:
        batch_op.alter_column('activityUuid',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('procedureVersionId',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('modelType',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('app_custom_config', schema=None) as batch_op:
        batch_op.alter_column('modelType',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('procedureVersionId',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('activityUuid',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)

    # ### end Alembic commands ###
